# Generated by Django 5.0.1 on 2024-01-25 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_auth_provider'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='user_type',
            field=models.CharField(choices=[('S', 'Student'), ('T', 'Teacher'), ('M', 'Manager')], default='S', max_length=1),
        ),
    ]
