# Generated by Django 5.0 on 2024-05-05 23:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_country_region_city'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='Country',
        ),
        migrations.RemoveField(
            model_name='user',
            name='city',
        ),
        migrations.RemoveField(
            model_name='user',
            name='region',
        ),
    ]
