# Generated by Django 5.0 on 2024-05-06 00:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_remove_user_country_remove_user_city_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='city',
            old_name='course',
            new_name='region',
        ),
        migrations.RenameField(
            model_name='region',
            old_name='course',
            new_name='country',
        ),
    ]
