# Generated by Django 5.0 on 2024-05-07 19:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_rename_course_city_region_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dictionary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='city',
            name='name',
        ),
        migrations.RemoveField(
            model_name='country',
            name='name',
        ),
        migrations.RemoveField(
            model_name='region',
            name='name',
        ),
        migrations.AddField(
            model_name='city',
            name='dictionary',
            field=models.ForeignKey(blank=True, default='', on_delete=django.db.models.deletion.CASCADE, to='accounts.dictionary'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='country',
            name='dictionary',
            field=models.ForeignKey(blank=True, default='', on_delete=django.db.models.deletion.CASCADE, to='accounts.dictionary'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='region',
            name='dictionary',
            field=models.ForeignKey(blank=True, default='', on_delete=django.db.models.deletion.CASCADE, to='accounts.dictionary'),
            preserve_default=False,
        ),
    ]
