# Generated by Django 5.0 on 2024-05-12 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_dictionary_remove_city_name_remove_country_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='image',
        ),
        migrations.AddField(
            model_name='user',
            name='height_image',
            field=models.ImageField(blank=True, null=True, upload_to='user_images/'),
        ),
        migrations.AddField(
            model_name='user',
            name='width_image',
            field=models.ImageField(blank=True, null=True, upload_to='user_images/'),
        ),
    ]
