# Generated by Django 5.0 on 2024-07-30 01:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Event', '0002_alter_learn_event_alter_speaker_event'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventsSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('session_id', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=225)),
                ('status', models.CharField(choices=[('L', 'Live'), ('B', 'Block')], default='L', max_length=1)),
            ],
        ),
    ]
