# Generated by Django 5.0 on 2024-07-30 01:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Event', '0003_eventssession'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventssession',
            name='name',
            field=models.CharField(blank=True, max_length=225, null=True),
        ),
    ]
