# Generated by Django 5.0 on 2024-08-29 16:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Event', '0007_eventssession_ip'),
    ]

    operations = [
        migrations.DeleteModel(
            name='EventsSession',
        ),
    ]
