# Generated by Django 5.0 on 2024-05-30 16:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('LiveCourses', '0005_remove_livecoursecouponcode_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userlivecourse',
            name='phone',
        ),
    ]
