# Generated by Django 5.0 on 2024-07-29 22:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LiveCourses', '0007_alter_ask_student'),
        ('Query', '0001_initial'),
        ('meetings', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='answr',
            name='Teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teacher_answrs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='answr',
            name='parent_comment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parent_comment_answrs', to='LiveCourses.ask'),
        ),
        migrations.AlterField(
            model_name='ask',
            name='course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='course_ask', to='LiveCourses.livecourse'),
        ),
        migrations.AlterField(
            model_name='ask',
            name='student',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='student_ask', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='base',
            name='course',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='course_base', to='LiveCourses.livecourse'),
        ),
        migrations.AlterField(
            model_name='base',
            name='timeline',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='timeline_base', to='LiveCourses.timeline'),
        ),
        migrations.AlterField(
            model_name='livecourse',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='author_live_course', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='livecourse',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='category_live_course', to='Query.category'),
        ),
        migrations.AlterField(
            model_name='livecoursecouponcode',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='live_coupon_course', to='LiveCourses.livecourse'),
        ),
        migrations.AlterField(
            model_name='livecoursefrequentlyasked',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='live_coupon_Freq_course', to='LiveCourses.livecourse'),
        ),
        migrations.AlterField(
            model_name='livecourserate',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_live_course_rates', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='livecoursereview',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_live_course_review', to='LiveCourses.livecourse'),
        ),
        migrations.AlterField(
            model_name='question',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_question', to='LiveCourses.livecourse'),
        ),
        migrations.AlterField(
            model_name='speaker',
            name='Teacher',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='teacher_speaker', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='timeline',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_timeline', to='LiveCourses.livecourse'),
        ),
        migrations.AlterField(
            model_name='timeline',
            name='meeting',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='meeting_timeline', to='meetings.meeting'),
        ),
        migrations.AlterField(
            model_name='userlivecourse',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_user_live_course', to='LiveCourses.livecourse'),
        ),
        migrations.AlterField(
            model_name='userlivecourse',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_user_live_course', to=settings.AUTH_USER_MODEL),
        ),
    ]
