# Generated by Django 5.0 on 2024-07-29 22:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LiveCourses', '0008_alter_answr_teacher_alter_answr_parent_comment_and_more'),
        ('meetings', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meeting',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_meetings', to='LiveCourses.livecourse'),
        ),
    ]
