# Generated by Django 5.0 on 2024-07-30 01:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meetings', '0003_meetingsession'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MeetingSession',
        ),
    ]
