# Generated by Django 5.0 on 2024-05-21 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Courses', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usercourse',
            name='date',
            field=models.DateField(auto_now=True),
        ),
    ]
