# Generated by Django 5.0 on 2024-05-30 12:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Courses', '0002_usercourse_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='couponcode',
            name='time',
        ),
    ]
