# Generated by Django 5.0 on 2024-07-29 22:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Courses', '0003_remove_couponcode_time'),
        ('Query', '0001_initial'),
        ('Quiz', '0004_remove_examcouponcode_time'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='couponcode',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_coupon_code', to='Courses.course'),
        ),
        migrations.AlterField(
            model_name='course',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='author_course', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='course',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='category_course', to='Query.category'),
        ),
        migrations.AlterField(
            model_name='course',
            name='exam',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='exam_course', to='Quiz.exam'),
        ),
        migrations.AlterField(
            model_name='coursesection',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='coursesection',
            name='title',
            field=models.CharField(blank=True, max_length=225),
        ),
        migrations.AlterField(
            model_name='episode',
            name='exam',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='episode_exam', to='Courses.episodequiz'),
        ),
        migrations.AlterField(
            model_name='episodequiz',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='episode_quiz_course', to='Courses.course'),
        ),
        migrations.AlterField(
            model_name='frequentlyasked',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='frequently_asked_course', to='Courses.course'),
        ),
        migrations.AlterField(
            model_name='instructors',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_instructor', to='Courses.course'),
        ),
        migrations.AlterField(
            model_name='instructors',
            name='teacher',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='instructor_teacher', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='rate',
            name='course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='course_Rate', to='Courses.course'),
        ),
        migrations.AlterField(
            model_name='usercourse',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_course_course', to='Courses.course'),
        ),
        migrations.AlterField(
            model_name='usercourse',
            name='student',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_course_student', to=settings.AUTH_USER_MODEL),
        ),
    ]
