# Generated by Django 5.0 on 2024-05-21 19:11

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Query', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Question_category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Exam',
            fields=[
                ('level', models.CharField(choices=[('Beginner', 'Beginner'), ('Intermediate', 'Intermediate'), ('Advanced', 'Advanced')], default='', max_length=20)),
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateField(auto_now=True)),
                ('active', models.BooleanField(default=False)),
                ('card_image', models.ImageField(blank=True, upload_to='files/images/Exam/card_image/image/%Y/%m/%d/')),
                ('intro_video', models.CharField(blank=True, max_length=100, null=True)),
                ('intro_image', models.FileField(blank=True, null=True, upload_to='files/Exam')),
                ('title', models.CharField(max_length=255, verbose_name='Exam Title')),
                ('description', models.TextField(verbose_name='Description')),
                ('price', models.IntegerField(default=0)),
                ('discount', models.IntegerField(default=0)),
                ('time_to_answer', models.IntegerField(default=60, verbose_name='Time to Answer ')),
                ('WrongAnswers', models.BooleanField(default=False)),
                ('tries', models.FloatField(default=1, verbose_name='tries')),
                ('Enroll', models.FloatField(default=1)),
                ('pixal_id', models.CharField(blank=True, max_length=500, null=True)),
                ('views', models.IntegerField(blank=True, default=0, null=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Exam', to='Query.category')),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_exams', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ExamCouponCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Code', models.CharField(max_length=100)),
                ('date', models.DateField(blank=True, null=True)),
                ('time', models.TimeField(blank=True, null=True)),
                ('Enroll', models.FloatField(default=1)),
                ('discount', models.IntegerField(default=0)),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Quiz.exam')),
            ],
        ),
        migrations.CreateModel(
            name='FrequentlyAsked',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField(blank=True, null=True)),
                ('answer', models.TextField(blank=True, null=True)),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Quiz.exam')),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('question_content', models.TextField(blank=True, null=True, verbose_name='Question Content')),
                ('question_image', models.ImageField(blank=True, null=True, upload_to='files/images/Question/question_images/image/%Y/%m/%d/', verbose_name='Question Image')),
                ('question_video_youtube', models.CharField(blank=True, max_length=300, null=True)),
                ('question_video', models.CharField(blank=True, max_length=500, null=True)),
                ('option_A', models.CharField(max_length=500)),
                ('option_B', models.CharField(max_length=500)),
                ('option_C', models.CharField(blank=True, max_length=500)),
                ('option_D', models.CharField(blank=True, max_length=500)),
                ('correct_option', models.CharField(choices=[('1', 'A'), ('2', 'B'), ('3', 'C'), ('4', 'D')], max_length=1)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='question', to=settings.AUTH_USER_MODEL)),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Quiz.question_category')),
            ],
        ),
        migrations.CreateModel(
            name='ExamSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.FloatField(blank=True, default=0, null=True, verbose_name='Exam Score')),
                ('time_taking', models.IntegerField(blank=True, default=0, null=True)),
                ('exam', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='Quiz.exam')),
                ('user', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='exam_submissions', to=settings.AUTH_USER_MODEL)),
                ('wrong_answers', models.ManyToManyField(blank=True, to='Quiz.question')),
            ],
        ),
        migrations.AddField(
            model_name='exam',
            name='questions',
            field=models.ManyToManyField(related_name='questions', to='Quiz.question'),
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='files/images/Review_images/image/%Y/%m/%d/')),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Quiz.exam')),
            ],
        ),
        migrations.CreateModel(
            name='UserExam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now=True)),
                ('date', models.DateField()),
                ('tries', models.FloatField(default=1, verbose_name='tries')),
                ('Paid', models.IntegerField(default=0)),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Quiz.exam')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrolled_exam', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
