# Generated by Django 5.0 on 2024-05-25 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Quiz', '0002_alter_userexam_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exam',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
