# Generated by Django 5.0 on 2024-05-30 12:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Quiz', '0003_alter_exam_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='examcouponcode',
            name='time',
        ),
    ]
