# Generated by Django 5.0 on 2024-05-28 15:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Email',
        ),
    ]
