# Generated by Django 5.0 on 2024-05-26 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EmailMarketing', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='subject',
            field=models.CharField(default='', max_length=300),
            preserve_default=False,
        ),
    ]
