# Generated by Django 5.0 on 2024-05-27 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EmailMarketing', '0003_groupad_remove_customer_campaign_campaign_groupad_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='groupad',
        ),
        migrations.AddField(
            model_name='campaign',
            name='customer',
            field=models.ManyToManyField(blank=True, to='EmailMarketing.customer'),
        ),
    ]
