# Generated by Django 5.0 on 2024-05-27 12:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('EmailMarketing', '0004_remove_customer_groupad_campaign_customer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='campaign',
            name='groupad',
        ),
    ]
