# Generated by Django 5.0 on 2024-07-29 22:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('EmailMarketing', '0005_remove_campaign_groupad'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Groupad',
        ),
    ]
