name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-22.04  # Use a specific stable version of Ubuntu

    steps:
      # Step 1: Check out the code from the repository
      - name: Check out the code
        uses: actions/checkout@v4

      # Step 2: Set up Docker Buildx, which is required for advanced Docker builds
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # Step 3: Log in to Docker Hub using credentials stored in GitHub Secrets
      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # Step 4: Build and push the backend Docker image
      - name: Build and Push backend Docker image
        run: |
          # Navigate to the backend directory
          cd backend
          ls  # Confirm the directory and list files for debugging
          
          # Build the Docker image for the backend service
          docker build -t mohamedeg/backendeducation:latest .
          if [ $? -ne 0 ]; then
            echo "Backend Docker image build failed"
            exit 1
          fi
          
          # Push the backend Docker image to Docker Hub
          docker push mohamedeg/backendeducation:latest
          if [ $? -ne 0 ]; then
            echo "Backend Docker image push failed"
            exit 1
          fi

      # Step 5: Build and push the frontend Docker image
      - name: Build and Push frontend Docker image
        run: |
          # Navigate to the frontend directory
          cd frontend
          ls  # Confirm the directory and list files for debugging
          
          # Build the Docker image for the frontend service
          docker build -t mohamedeg/frontendeducationa:latest .
          if [ $? -ne 0 ]; then
            echo "Frontend Docker image build failed"
            exit 1
          fi
          
          # Push the frontend Docker image to Docker Hub
          docker push mohamedeg/frontendeducationa:latest
          if [ $? -ne 0 ]; then
            echo "Frontend Docker image push failed"
            exit 1
          fi