name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-22.04  # Use a specific stable version of Ubuntu

    steps:
      # Step 1: Check out the code from the repository
      - name: Check out the code
        uses: actions/checkout@v4

      # Step 2: Set up Docker Buildx (optional step, if using buildx)
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # Step 3: Log in to Docker Hub using credentials stored in GitHub Secrets
      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # Step 4: Build and push the backendeducation Docker image
      - name: Build and Push backendeducation Docker Image
        env:
          REPOSITORY: backendeducation  
          IMAGE_TAG: latest
        run: |
          cd backend
          pwd 
          docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/$REPOSITORY:$IMAGE_TAG .
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/$REPOSITORY:$IMAGE_TAG

      # Step 5: Build and push the frontendeducation Docker image
      - name: Build and Push Frontend Docker Image
        env:
          REPOSITORY: frontendeducation  # Ensure repository name is consistent
          IMAGE_TAG: latest
        run: |
          cd frontend
          pwd
          docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/$REPOSITORY:$IMAGE_TAG .
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/$REPOSITORY:$IMAGE_TAG